//
//  MovieListInteractor.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/21/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
import UIKit
protocol MovieListInteractorInput {
    var requestedMovie: String? {set get}

}

protocol MovieListInteractorOutput {

}

protocol MovieListDataSource {
       
}

protocol MovieListDataDestination {
    
}

class MovieListInteractor: MovieListInteractorInput, MovieListDataSource, MovieListDataDestination {
    
    var output: MovieListInteractorOutput?
    var worker = MovieListWorker()
    private var searchedMovies = [Movie]()
    var requestedMovie: String?

    
    // MARK: Do something
    func fetchMoviesData(completion: @escaping () ->()){
        worker.getMovie(movie: requestedMovie!) { [weak self] (result) in
            switch result{
            case .success(let listOf):
                self?.searchedMovies = listOf.movies
                completion()
            case.failure(let error):
                print("error processing data\(error)")
                
            }
        }
    }
    func numberOfRowInSection(section: Int) -> Int{
        if searchedMovies.count != 0{
            return searchedMovies.count
        }
        return 0
    }
    func cellForRowAt(indexPath: IndexPath) -> Movie{
        return searchedMovies[indexPath.row]
    }
    

}
