//
//  MovieListWorker.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/22/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

class MovieListWorker {
    // MARK: Business Logic

        }

