//
//  MovieListConfigurator.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/21/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension MovieListInteractor: MovieListViewControllerOutput, MovieListRouterDataSource, MovieListRouterDataDestination {
    
}

extension MovieListPresenter: MovieListInteractorOutput {
}

class MovieListConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = MovieListConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: MovieListViewController) {
        
        let presenter = MovieListPresenter()
        presenter.output = viewController
        
        let interactor = MovieListInteractor()
        interactor.output = presenter
        
        let router = MovieListRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
