//
//  MovieListInteractor.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/21/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
import UIKit
protocol MovieListInteractorInput {
    var results : [Movie]? {set get}

}

protocol MovieListInteractorOutput {
    func passDataToModeling(movies: [Movie])

}

protocol MovieListDataSource {
       
}

protocol MovieListDataDestination {
    
}

class MovieListInteractor: MovieListInteractorInput, MovieListDataSource, MovieListDataDestination {
    var results: [Movie]?
    
    var output: MovieListInteractorOutput?
}
