//
//  MovieListPresenter.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/21/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol MovieListPresenterInput {
    func passDataToModeling(movies: [Movie])
}

protocol MovieListPresenterOutput: class {
    func presentData(movies: [Movie])
}

class MovieListPresenter: MovieListPresenterInput {
    func passDataToModeling(movies: [Movie]) { 
        output?.presentData(movies: movies)
    }
    
    
    weak var output: MovieListPresenterOutput?
    
    // MARK: Presentation logic
    
    
}
