//
//  MovieListRouter.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/21/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol MovieListRouterInput {
    
}

protocol MovieListRouterDataSource: class {
    
}

protocol MovieListRouterDataDestination: class {
    
}

class MovieListRouter: MovieListRouterInput {
    
    let mainStoryBoard = UIStoryboard(name: "Main", bundle: nil)
    weak var viewController: MovieListViewController!
    weak private var dataSource: MovieListRouterDataSource!
    weak var dataDestination: MovieListRouterDataDestination!
    
    init(viewController: MovieListViewController, dataSource: MovieListRouterDataSource, dataDestination: MovieListRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
    func navigateToMovieList(navigationController : UINavigationController?){
        let movieDetailsVC = mainStoryBoard.instantiateViewController(withIdentifier: "MovieDetailsViewController") as! MovieDetailsViewController
//        movieDetailsVC.output?.movies = viewController.output?.results ?? ""
        navigationController?.pushViewController(movieDetailsVC, animated: true)
    }
    
}
