//
//  MovieListWorker.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/22/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

class MovieListWorker {
    // MARK: Business Logic
//    var api = API()
//    func fetchMovieData(movie: String,completion: @escaping () ->()){
//        api.getMovie(movie: movie) { [weak self] (result) in
//            switch result{
//            case .success(let listOf):
////                delegate?.addNewElementToSearchHistory(add: movieName)
////                self?.results = listOf.movies
////                self?.output?.passDataToModeling(movies: (self?.results)!)
//                completion()
//            case.failure(let error):
//                print("error processing data\(error)")
//            }
//        }
//        }
        }

