//
//  MovieDetailsModels.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/21/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct MovieDetailsModel{
    
    struct Request {
        
    }
    
    struct Response {
        
    }
    
    struct ViewModel {
        let movieTitle : String?
        let relaseDate : String?
        let MovieOverview : String?
        let moviePoster : String?
        let rate : Double?
    }
}

