//
//  MovieDetailsRouter.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/21/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol MovieDetailsRouterInput {
    
}

protocol MovieDetailsRouterDataSource: class {
    
}

protocol MovieDetailsRouterDataDestination: class {
    
}

class MovieDetailsRouter: MovieDetailsRouterInput {
    
    weak var viewController: MovieDetailsViewController!
    weak private var dataSource: MovieDetailsRouterDataSource!
    weak var dataDestination: MovieDetailsRouterDataDestination!
    
    init(viewController: MovieDetailsViewController, dataSource: MovieDetailsRouterDataSource, dataDestination: MovieDetailsRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
