//
//  MovieDetailsViewController.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/21/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol MovieDetailsViewControllerInput {
}

protocol MovieDetailsViewControllerOutput {
}

class MovieDetailsViewController: UIViewController, MovieDetailsViewControllerInput {
    var output: MovieDetailsViewControllerOutput?
    var router: MovieDetailsRouter?
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        MovieDetailsConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    //outlets
    @IBOutlet weak var posterImageView: UIImageView!
    
    

    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: Requests
    
    
    // MARK: Display logic
    
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension MovieDetailsViewController: MovieDetailsPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
