//
//  MovieDetailsInteractor.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/21/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol MovieDetailsInteractorInput {
var selectedMovie: Movie? {set get}
}

protocol MovieDetailsInteractorOutput {
    func passDataToModeling(movie: Movie)

}

protocol MovieDetailsDataSource {
    
}

protocol MovieDetailsDataDestination {
    
}

class MovieDetailsInteractor: MovieDetailsInteractorInput, MovieDetailsDataSource, MovieDetailsDataDestination {
    var selectedMovie: Movie?
    
    var output: MovieDetailsInteractorOutput?
    
    // MARK: Business logic
    
    func loadMovieData(){
        output?.passDataToModeling(movie: selectedMovie!)
    }

}
