//
//  SearchMovie1Models.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/21/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct MovieModel : Codable {
        let movies : [Movie]
        private enum CodingKeys: String, CodingKey{
            case movies = "results"
    }
}
    struct Movie : Codable
    {
        var title : String?
        var releaseDate : String?
        var posterPath: String?
        var rate : Double?
        var overview : String?
    
        
        enum CodingKeys: String, CodingKey{
            case title
            case overview
            case releaseDate = "release_date"
            case posterPath = "poster_path"
            case rate = "vote_average"
            
        }
    }


