//
//  SearchMoviePresenter.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/21/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol SearchMoviePresenterInput {
    
}

protocol SearchMoviePresenterOutput: class {
    
}

class SearchMoviePresenter: SearchMoviePresenterInput {
    
    weak var output: SearchMoviePresenterOutput?
    
    // MARK: Presentation logic
    
}
