//
//  SearchMovieModels.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/18/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SearchMovie
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
        
    }
    struct ViewModel
    {
    }
  }
}

struct MoviesData : Codable {
    let movies : [Movie]
    private enum CodingKeys: String, CodingKey{
        case movies = "results"
    }
}

struct Movie : Codable
{
    var title : String?
    var releaseDate : String?
    var posterPath: String?
    var rate : Double?
    var overview : String?
    
    enum CodingKeys: String, CodingKey{
        case title
        case overview
        case releaseDate = "release_date"
        case posterPath = "poster_path"
        case rate = "vote_average"
        
    }
}
