//
//  SearchMovieInteractor.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/18/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com

import UIKit

protocol SearchMovieBusinessLogic
{
  func doSomething(request: SearchMovie.Something.Request)
}

protocol SearchMovieDataStore
{
  //var name: String { get set }
}

class SearchMovieInteractor: SearchMovieBusinessLogic, SearchMovieDataStore
{
  var presenter: SearchMoviePresentationLogic?
  var worker: SearchMovieWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SearchMovie.Something.Request)
  {
    worker = SearchMovieWorker()
    worker?.doSomeWork()
    
    let response = SearchMovie.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
