//
//  SearchMoviePresenter.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/21/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol SearchMoviePresenterInput {
    func passDataToModeling(movies: [Movie])

}

protocol SearchMoviePresenterOutput: class {
    func presentData(movies: [Movie])
}

class SearchMoviePresenter: SearchMoviePresenterInput {
    
    weak var output: SearchMoviePresenterOutput?
    
    // MARK: Presentation logic
    func passDataToModeling(movies: [Movie]){
        output?.presentData(movies: movies)
        print("done")
    }
}
