//
//  SearchMovie1Interactor.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/21/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
import UIKit
protocol SearchMovieInteractorInput {
    var searchedMovie: String? {set get}
}

protocol SearchMovieInteractorOutput {
    func passDataToModeling(movies: [Movie])
}

protocol SearchMovieDataSource {
    
}

protocol SearchMovieDataDestination {
    
}

class SearchMovieInteractor: SearchMovieInteractorInput, SearchMovieDataSource, SearchMovieDataDestination {
    var searchedMovie: String?
    var output: SearchMovieInteractorOutput?
    var worker = SearchMovieWorker()
    var results : [Movie]?
    
    // MARK: Do something
    func fetchMoviesData(completion: @escaping () ->()){
        worker.getMovie(movie: searchedMovie!) { [weak self] (result) in
            switch result{
            case .success(let listOf):
                self?.results = listOf.movies
                self?.output?.passDataToModeling(movies: (self?.results)!)
                completion()
            case.failure(let error):
                print("error processing data\(error)")
            }
        }
    }
}
