//
//  SearchMovieRouter.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/18/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchMovieRoutingLogic
{
  func routeToListView(segue: UIStoryboardSegue?)
}

protocol SearchMovieDataPassing
{
  var dataStore: SearchMovieDataStore? { get }
}

class SearchMovieRouter: NSObject, SearchMovieRoutingLogic, SearchMovieDataPassing
{
    func routeToListView(segue: UIStoryboardSegue?) {
        routeToMovieList(segue: nil)
    }
    
  weak var viewController: SearchMovieViewController?
  var dataStore: SearchMovieDataStore?
  
  // MARK: Routing

    func routeToMovieList(segue: UIStoryboardSegue?)
    {
      if let segue = segue {
//        _ = segue.destination as! MovieListViewController
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToMovieList(source: dataStore!, destination: &destinationDS)
      } else {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "MovieListViewController") as! MovieListViewController
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        navigateToMovieList(source: viewController!, destination: destinationVC)
      }
    }
    // MARK: Navigation
    
    func navigateToMovieList(source: SearchMovieViewController, destination: MovieListViewController)
    {
      source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
//    
//    func passDataToMovieList(source: SearchMovieDataStore, destination: inout MovieListDataStore)
//    {
//      destination.name = source.name
//    }
}
