//
//  SearchMoviePresenter.swift
//  Movie Finder
//
//  Created by Esraa Gamal on 10/18/20.
//  Copyright (c) 2020 Esraa Gamal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchMoviePresentationLogic
{
  func presentSomething(response: SearchMovie.Something.Response)
}

class SearchMoviePresenter: SearchMoviePresentationLogic
{
  weak var viewController: SearchMovieDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SearchMovie.Something.Response)
  {
    let viewModel = SearchMovie.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
